export const wordsDefs = [
    { word: "Absolute path", def: "It is one that starts from the main directory" },
    { word: "Alias", def: "A nickname for common commands" },
    { word: "Appending flags", def: "A way to add the data of the file without erasing existing data" },
    { word: "Bash", def: "The language used to interact with the shell" },
    { word: "CLI", def: "Command line interpreter" },
    { word: "Command line", def: "A text interface program for a computer that inputs text commands and translates them to the operating system" },
    { word: "Escape characters", def: "A concept that means that the next character after the back tick should be treated literally" },
    { word: ".exe", def: "A file extension found in Windows for an executable file " },
    { word: "Groups", def: "A collection of users" },
    { word: "GUI", def: "A graphical user interface" },
    { word: "Hidden files", def: "A set of files that are not visible either to avoid alteration or simply because you don’t want someone to see them" },
    { word: "Hot key", def: "A keyboard shortcut that does a particular task" },
    { word: "I/O Streams", def: "An input stream handles data flowing into and out of a program" },
    { word: "Parameter", def: "A value that is associated with a command " },
    { word: "Parent directory & child directories", def: "A parent directory is a directory that houses all subsequent child directories" },
    { word: "Paths", def: "A main directory that branches off and holds other directories and files" },
    { word: "Prompt", def: "A prompt shows you which directory you’re currently in" },
    { word: "Regular expression", def: "A pattern matching language that describes words, phrases, or more complicated patterns; regular expressions are used to help you do advanced pattern based selection" },
    { word: "Relative path", def: "It is a path from your current directory" },
    { word: "Root directory", def: "A parent directory for all other directories in a file system" },
    { word: "Shell", def: "A shell is a command line interpreter for Linux" },
    { word: "Standard error (stderr)", def: "A data stream that redirect the output of error messages in a different output stream. It works both in Linux and Windows" },
    { word: "Standard In (stdin)", def: "A data stream in which the input that you provide through the keyboard goes to the standard in stream of the process that you're interacting with. It works both in Linux and Windows" },
    { word: "Standard out (stdout)", def: "A data stream that when a process creates output, it adds data to the standard out stream, which flows out of the process. It works both in Linux and Windows" },
    { word: "Stdin, stdout, stderr", def: "Three data streams created when you launch a Linux command" },
    { word: "Subdirectories", def: "A directory below or at a deeper level in the directory hierarchy" },
    { word: "Tab completion", def: "A way to auto-complete a command or file names and directories " },
    { word: "Wildcard", def: "A character that is used to help select files based on a certain pattern" },
    { word: "Windows Search service", def: "A service that indexes files on your computer by looking through them on a schedule" },
    { word: "ACL", def: "Access Control Lists" },
    { word: "Administrator", def: "A user that has complete control over a machine" },
    { word: "Biometric data", def: "A way of protecting your accounts and information using biometric data such as facial recognition and fingerprint" },
    { word: "Computer management", def: "A tool that lets you manage a local or remote computer" },
    { word: "DACL", def: "Discretionary Access Control List" },
    { word: "File permissions", def: "A process for setting permissions for who has access to certain files" },
    { word: "Full control", def: "A user or group with full control that can do anything they want to files" },
    { word: "Inherit only", def: "A permission group that means that a DACL will be inherited, but not applied to a container" },
    { word: "List folder contents", def: "A command that will execute and list folder contents and is an alias for Read and Execute" },
    { word: "Mobile device management", def: "A system used to apply and enforce rules about how the device has to be configured and used" },
    { word: "Modify", def: "An umbrella permission that includes read and execute and write" },
    { word: "Primary account", def: "The initial account you made during setup" },
    { word: "Read and execute permission", def: "Permissions that grant you access to read the file that exists and execute it if its runnable" },
    { word: "Read permission", def: "Permissions that grant you access to read the file that exists" },
    { word: "Root user", def: "It is the first user that gets automatically created when we install a Linux OS and has all the privileges on the OS. Also called the super user. There's technically only one superuser or root account, but anyone that's granted access to use their powers can be called a superuser too" },
    { word: "SACL’s", def: "System Access Control List" },
    { word: "Simple permissions", def: "Special or specific permissions" },
    { word: "Single sign on (SSO)", def: "An account that grants you access to multiple accounts without require constant entry of a password or username" },
    { word: "Standard user", def: "A user who is given access to the machine but has restricted access to do thing like install software or change certain setting" },
    { word: "Windows domain", def: "A network of computers and users that are added to a central database" },
    { word: "Write permission", def: "A permission that allows you to make changes to a file" },
    { word: "App Store apps", def: "A Package Manager that acts as a repository" },
    { word: "App store repository", def: "A app store service that also acts as a repository" },
    { word: "App stores", def: "A central managed marketplace for app developers to publish and sell mobile apps" },
    { word: "APPX", def: "An APPX is another way to package contents of a file to act like a unit of distribution" },
    { word: "Archive", def: "An archive is comprised of one or more files that are compressed into a single file" },
    { word: "Block devices", def: "A system that acts like USB drives and hard drive by transmitting data" },
    { word: "Cache", def: "The assigned stored location for recently or frequently accessed data; on a mobile app it is where anything that was changed or created with that app is stored " },
    { word: "Character devices", def: "A way to transmit data character by character like a keyboard and mouse" },
    { word: "Chocolatey", def: "A third party package manager for Windows" },
    { word: "Closed source packages", def: "A source code that does not allow public access" },
    { word: "Debian(.deb)", def: "A Debian package is packaged as a .deb file" },
    { word: "Device manager", def: "A console management system for your device" },
    { word: "Driver", def: "Used to help our hardware devices interact with our Operating System" },
    { word: "Dynamic-link libraries", def: "Programs that want to use functionality that the code provides can tap into it if they need to (shared libraries) " },
    { word: "Enterprise app management", def: "A management system that allows an organization to distribute custom mobile apps" },
    { word: "Executable file", def: "A file containing instructions for a computer to execute when they’re run" },
    { word: "Hardware ID", def: "A special string of characters assigned to hardware" },
    { word: "Having dependencies", def: "A process of counting on other pieces of software to make an application work since one bit of code depends on another in order to work" },
    { word: "Installing from source", def: "A process of installing from a source" },
    { word: "Kernel module", def: "It extends the kernel's functionality so developers don't have to actually touch the Linux kernel" },
    { word: "Library", def: "A way to package a bunch of useful code that someone else wrote" },
    { word: "Manifest", def: "A library used if an application needs to use a shared library" },
    { word: "Microsoft Install Package(.msi) and MSI files", def: "Microsoft Install Package is a file extension used to guide a program called Windows Installer in the installation, maintenance, and removal of programs of the windows operating systems. MSI files are a combination of of databases that contain installation instructions in different tables along with all the files" },
    { word: "Mobile applications", def: "Software that is distributed on mobile OS devices " },
    { word: "Packaged archives", def: "The core or source software files that are compressed into one file" },
    { word: "Packaged managers", def: "An application that makes package installation and removal easier" },
    { word: "Personal package archives", def: "A software repository for uploading source packages to be built and published " },
    { word: "Portable Executable (PE) format", def: "Windows unique version of .exe" },
    { word: "Process monitoring", def: "A way of monitoring what processes are happening during installation" },
    { word: "Repository", def: "A server that acts like a central storage location for packages" },
    { word: "SD devices", def: "Mass storage devices like hard drives" },
    { word: "Security patch", def: "A piece of software that is meant to fix up a security hole" },
    { word: "Side-by-side assemblies", def: "A system that manages most shared libraries and resources on Windows and supports access to multiple versions of the same shared library automatically" },
    { word: "Side-loading", def: "A process of installing mobile apps directly without using an app store" },
    { word: "Sysinternals package", def: "A set of tools released by Microsoft that can help you troubleshoot" },
    { word: "Windows store", def: "A Windows store is an application repository or warehouse where you can download and install universal Windows platform apps" },
    { word: "Windows update client service", def: "System that runs in the background on your computer to download and install updates and patches for your operating system" },
    { word: "Command line mode", def: "When you are able to run commands while still in your current shell" },
    { word: "Data", def: "Actual content of a file" },
    { word: "Data buffer", def: "A region of RAM that’s used to temporarily store data while it’s being moved around" },
    { word: "Defragmentation", def: "A process of taking all the files stored on a given disk and reorganizing them into neighboring locations" },
    { word: "Disk Management utility", def: "Native tool for Windows that helps with managing disk space" },
    { word: "File record number", def: "The index of the files entry in the MFT" },
    { word: "File system", def: "Used to keep track of files and file storage on a disk" },
    { word: "Hard link", def: "When created in NTFS, an entry is added to the MFT that points to the linked file record number, not the name of the file. This means the file name of the target can change and the hard link will still point to it" },
    { word: "Inode", def: "A file structure for metadata and files" },
    { word: "Interactive mode", def: "When the parted tool launches you into a separate program" },
    { word: "Master boot record (MBR)", def: "a traditional partition table within a storage disk that lets you have volume sizes of 2 terabytes or less and is mostly used in the Windows OS" },
    { word: "Master file table (MFT)", def: "A way NTFS stores and represents the files you’re working with on your operating system" },
    { word: "Memory manager", def: "A Windows OS program that helps manage virtual memory " },
    { word: "Metadata", def: "Tells us everything we need to know about a file, including who created it, when it was last modified, who has access to it, and what type of file it is." },
    { word: "Mounting", def: "Making a file or hard disk accessible to the computer" },
    { word: "Partition table", def: "How the disk is partitioned on an OS" },
    { word: "Shortcut", def: "An entry in the MFT that has a reference to some destination, so that when you open it up, you get taken to that destination" },
    { word: "Softlinks", def: "A shortcut in Linux, that allows us to link to another file using a file name" },
    { word: "Swap space", def: "The allocated space where the virtual memory is stored on the hard drive when the amount of physical memory space is used up or full" },
    { word: "Symbolic links", def: "Work similarly to shortcuts, but at the file system level. The key difference is that the operating system treats them like substitutes for the file they're linked to in almost every meaningful way" },
    { word: "System properties", def: "A control panel applet that allows you to edit the size and number and location of paging files" },
    { word: "Trim", def: "A command to delete unused data blocks so the space can be used for the computer’s storage needs" },
    { word: "UEFI", def: "A new standard for BIOS" },
    { word: "UUID", def: "Universally Unique ID" },
    { word: "Virtual memory", def: "A combination of hard drive space and RAM that acts like memory which our processes can use" },
    { word: "Volume", def: "A format for a filesystem on a partition" },
    { word: "Background processes/Daemon processes", def: "Processes that run or take place in the background" },
    { word: "Client/Server runtime subsystem", def: "System that handles running Windows GUI and Command line" },
    { word: "Environment", def: "Whatever settings or variables a child process inherits from the parent’s process" },
    { word: "Multilingual user interface", def: "Interface that offers and support different languages" },
    { word: "Processes", def: "Help the computer run programs " },
    { word: "Process Explorer", def: "A utility Microsoft created to let IT support specialists and system administrators look at running processes" },
    { word: "Process ID", def: "Unique identifier for processes on your computer" },
    { word: "Programs", def: "The applications that we can run" },
    { word: "Resource monitoring", def: "The most common way to quickly take a peek at how system resources are doing" },
    { word: "Session manager subsystem", def: "Process that is in charge of setting some stuff up to work for the OS" },
    { word: "Signal", def: "A way to tell a process that something has just happened" },
    { word: "Suspended apps", def: "A command that will tell the OS to suspend background mobile apps" },
    { word: "Task Manager", def: "A Windows utility that allows you to gain information about what tasks you have running in the background " },
    { word: "Termination signal", def: "A kill command that will stop whatever process you tell it to" },
    { word: "Cloud computing", def: "The concept and technological approach of accessing data, using applications, storing files, etc. from anywhere in the world as long as you have an internet connection" },
    { word: "Data center", def: "A facility that stores hundreds, if not thousands of servers" },
    { word: "Deployment", def: "Hardware is set up so that the employee can do their job" },
    { word: "IT Infrastructure", def: "The software, the hardware, network, and services required for an organization to operate in an enterprise IT environment" },
    { word: "KVM Switch", def: "Keyboard, video, & mouse switch that looks like a hub that you can connect multiple computers to and control using one keyboard, mouse, and monitor" },
    { word: "Maintenance", def: "Where software is updated and hardware issues are fixed if, and when, they occur" },
    { word: "Procurement", def: "Hardware is purchased or reused for an employee" },
    { word: "Production", def: "The parts of the infrastructure where certain services are executed and serve to its users production" },
    { word: "Reproduction case", def: "Recreating an error to test a solution to make sure the problem is gone after a fix has been applied" },
    { word: "Retirement", def: "Hardware becomes unusable or no longer needed, and it needs to be properly removed from the fleet" },
    { word: "Rollback", def: "Reverting to the previous state before you made changes" },
    { word: "Secondary or stand-by machine", def: "A machine that is the same as a production machine, but won't receive any traffic from actual users until enabled" },
    { word: "Server", def: "Software or a machine that provides services to other software or machines" },
    { word: "System Administration", def: "The field in IT that is responsible for maintaining reliable computer systems, in a Multi-user environment" },
    { word: "Test environment", def: "A virtual machine running the same configuration as a production environment, but isn't actually serving any users of the service" },
    { word: "Domain Name System (DNS)", def: "A global and highly distributed network service that resolves strings of letters, such as a website name, into an IP address" },
    { word: "Intranet", def: "An internal network inside a company, accessible if you are on a company’s network" },
    { word: "NTP", def: "Network Time Protocol, keeping clocks synchronized on machines connected to a network" },
    { word: "Proxy server", def: "An intermediary between a company's network and the Internet, receiving network traffic and relaying that information to the company network" },
    { word: "Server operating systems", def: "Regular operating systems that are optimized for server functionality" },
    { word: "Autoscaling", def: "A system that allows the service to increase or reduce capacity as needed, while the service owner only pays for the cost of the machines that are in use at any given time" },
    { word: "Databases", def: "Databases allow us to store query, filter, and manage large amounts of data" },
    { word: "File storage service", def: "Allows to centrally store files and manage access between files and groups" },
    { word: "HTTPS", def: "Hypertext Transfer Protocol Secure is a secure version of HTTP that ensures the communication your web browser has with the website is secured through encryption" },
    { word: "HTTP status code", def: "The codes or numbers that indicate some sort of error or info messages that occurred when trying to access a web resource" },
    { word: "Hybrid cloud", def: "Used to describe situations where companies might run things like their most sensitive proprietary technologies on a private cloud or on premise while entrusting their less sensitive servers to a public cloud" },
    { word: "Load balancer", def: "Ensures that each VM receives a balanced number of queries" },
    { word: "Network file system", def: "A protocol that enables files to be shared over a network" },
    { word: "Platform services", def: "A platform for developers to completely build and deploy software applications, without having to deal with OS maintenance, server hardware, networking or other services that are needed to use the platform tools" },
    { word: "Private cloud", def: "When a company owns the services and the rest of the cloud infrastructure, whether on-site or in a remote data center" },
    { word: "Public cloud", def: "The cloud services provided by a third party" },
    { word: "Regions", def: "A geographical location containing a number of data centers" },
    { word: "Software services", def: "The services that employees use that allow them to do their daily job functions, such as word processors, Internet browsers, email clients, chat clients, and more" },
    { word: "Web server", def: "A web server stores and serves content to clients through the Internet" },
    { word: "AAA (authentication, authorization, accounting)", def: "The services that the directory services provide to all the computers within a company or organization" },
    { word: "Active directory (AD)", def: "The Microsoft alternative to directory services that offers customization and added features for the Windows platform" },
    { word: "Active directory users and computers (ADUC)", def: "The client tools that are used for accessing and administering a directory server" },
    { word: "Advanced group policy management (AGPM)", def: "A set of add-on tools from Microsoft that gives some added provision control abilities in GPMC" },
    { word: "Bind operation", def: "The operation which authenticates clients to the directory server" },
    { word: "Central management", def: "A central service that provides instructions to all of the different parts of my IT infrastructure" },
    { word: "Change management process", def: "The process to notify others in the organization about the changes that you are about to make" },
    { word: "Computer configuration", def: "Contained within a Group Policy Object (GPO)" },
    { word: "Configuration management", def: "The creation of rules about how things should work in your organization, such as printers, configure software, or mounting network file systems" },
    { word: "Default domain control policy", def: "One of the two GPOs that are created when a new Active Directory domain has been made" },
    { word: "Delegation", def: "The administrative tasks that you need to perform a lot as a part of your day to day job but you don't need to have broad access to make changes in AD" },
    { word: "Directory Access Protocol (DAP)", def: "A protocol that is included in the X.500 directory standard from 1988" },
    { word: "Directory Information Shadowing Protocol (DISP)", def: "A protocol that is included in the X.500 directory standard from 1988" },
    { word: "Directory Operational Bindings Management Protocol (DOBMP)", def: "A protocol that is included in the X.500 directory standard from 1988" },
    { word: "Directory server", def: "The server that contains a lookup service that provides mapping between network resources and their network addresses" },
    { word: "Directory services", def: "A lookup service contained in a network server that provides mapping between network resources and their network addresses" },
    { word: "Directory System Protocol (DSP)", def: "A protocol that is included in the X.500 directory standard from 1988" },
    { word: "Distribution group", def: "A group that is only designed to group accounts and contacts for email communication" },
    { word: "DNS records", def: "A DNS request for the SRV records matching the domain that it's been bound to" },
    { word: "Domain admin", def: "The administrators of the Active Directory domain" },
    { word: "Domain computers", def: "All the computers joined to the domain except domain controllers" },
    { word: "Domain controllers (DC)", def: "The service that hosts copies of the Active Directory database" },
    { word: "Domain local", def: "The tool used to assign permission to a resource" },
    { word: "Domain users", def: "A group that contains every user account in the domain" },
    { word: "Enterprise admin", def: "The administrators of the Active Directory domain that has permission to make changes to the domain that affect other domains in a multi-domain forest" },
    { word: "Enterprise mobility management (EMM)", def: "A system that can create and distribute policies and MDMs" },
    { word: "Fast logon optimization", def: "The group policy engine that applies policy settings to a local machine may sacrifice the immediate application of some types of policies in order to make logon faster" },
    { word: "Flexible single-master operations (FSMO)", def: "The single domain controller that has been tasked with making changes to the AD database that can only be made by one DC at a time" },
    { word: "Forest", def: "The hierarchy above a domain that contains multiple domains, allowing accounts to share resources between domains that are in the same forest" },
    { word: "Functional levels", def: "The different versions of Active Directory, a functional level that describes the features that it supports" },
    { word: "Global", def: "The tool that is used to group accounts into a role" },
    { word: "Group policy management console (GPMC)", def: "The tools used for creating and viewing a group policy object" },
    { word: "Group policy objects (GPO)", def: "The ways to manage the configuration of Windows machines, referring to the objects that represent things in your network that you want to be able to reference or manage" },
    { word: "Group policy settings reference", def: "A spreadsheet that details the GPO policies and preferences that are available and where to find them" },
    { word: "Group scope", def: "The way that group definitions are replicated across domains" },
    { word: "Import", def: "Moving a backup of the test example policy to the production example policy" },
    { word: "Kerberos", def: "A network authentication protocol that uses tickets to allow entities to prove their identity over potentially insecure channels to provide mutual authentication" },
    { word: "LDAP data interchange format", def: "The tool that allows you to authenticate, add, remove users, groups, computers and so on in a directory service" },
    { word: "LDAP Entry", def: "A collection of information that's used to describe something" },
    { word: "LDIF files", def: "A text file that lists attributes and values that describe something" },
    { word: "Lightweight Directory Access Protocol (LDAP)", def: "An open industry-standard protocol for accessing and maintaining directory services; the most popular open-source alternative to the DAP" },
    { word: "Linked", def: "A GPO that all of the computers or users under a domain, site, or OU will have a policy applied" },
    { word: "MDM policy", def: "The profiles that contain settings for the device" },
    { word: "MDM profile", def: "The policies that contain settings for the device" },
    { word: "One-way cryptographic hash", def: "The method used by AD to store passwords" },
    { word: "OpenLDAP (lightweight directory access protocol)", def: "An open source and free directory service" },
    { word: "Organizational units (OU)", def: "A hierarchical model of objects and containers that can contain objects or more organizational units" },
    { word: "Parent group", def: "Groups that are principal groups and contain other groups" },
    { word: "PHPLDAPadmin", def: "A tool to manage OpenLDAP" },
    { word: "Policies", def: "Settings that are reapplied every few minutes, and aren’t meant to be changed even by the local administrators" },
    { word: "Precedence", def: "When computers are processing the Group Policy Objects that apply to them, all of these policies will be applied in a specific order based on a set of precedents rules" },
    { word: "Read-write replicas", def: "Domain controllers in the Active Directory network that each have a complete copy of the AD database and are able to make changes to it" },
    { word: "Remote wipe", def: "A factory reset that you can trigger from your central MDM rather than having to do it in person on the device" },
    { word: "Replication", def: "The store directory data is copied and distributed across a number of physically distributed servers but still appears as one unified data store for querying and administering" },
    { word: "Replication failure", def: "A reason that a GPO might fail to apply as expected" },
    { word: "Reset", def: "When an SysAdmin restores or resets the password of a user" },
    { word: "Restart", def: "A command that will let the machine reboot to complete a domain join" },
    { word: "Resultant set of policy (RSOP)", def: "The policy that forms when all of the group policies have been grouped together for a specific machine and apply precedence rules to them" },
    { word: "Role-based access control (RBAC)", def: "The process of changing a persons group that they are a part of when they have changed roles within a company to limit or change their access to resources" },
    { word: "RSOP report", def: "The process of troubleshooting group policy and comparing what you expect to be applied to a computer and the resultant set of policy report" },
    { word: "Security account manager (SAM)", def: "A database in windows that stores user names and password" },
    { word: "Security filtering", def: "A tool to make group policies apply more selectively" },
    { word: "Security group", def: "One of the two categories that groups in Active Directories can be part of, they can contain user accounts, computer accounts or other security groups" },
    { word: "Security principal", def: "Any entity that can be authenticated by the system, such as a user account, a computer account, or a thread or process that runs in the security context of a user or computer account" },
    { word: "Service discovery", def: "One of the services that the domain controller provides to the clients" },
    { word: "Simple authentication and security layer (SASL)", def: "The authentication method that can employ the help of security protocols like TLS, it requires the client and the directory server to authenticate using some method" },
    { word: "SRV records", def: "A service record used to define the location of various specific services" },
    { word: "Systems administrator (sysadmin)", def: "A person who works only in system administration, configuring servers, monitoring the network, provisioning, or setting up new users in computers and taking responsibility of systems" },
    { word: "Universal", def: "The tool that is used to group global roles in a forest" },
    { word: "User configuration", def: "Contained within a Group Policy Object (GPO)" },
    { word: "User Groups", def: "The management of resources on a computer and on a network through organizing user accounts into various groups" },
    { word: "Windows management instrumentation (WMI)", def: "The container that is used to define powerful targeting rules for your GPO" },
    { word: "Windows registry", def: "A hierarchical database of settings that Windows, and Windows applications, use for storing configuration data" },
    { word: "WMI filter", def: "A tool to make group policies apply more selectively on the configuration of the computer" },
    { word: "Work group computer", def: "A Windows computer that isn't joined to a domain" },
    { word: "X.500 directory", def: "The agreed upon directory standard that was approved in 1988 that includes, DAP, DSP, DISP, DOP, DAP, and LDAP" },
    { word: "BackupAndRestore", def: "A Microsoft offer and first party solution that has modes of operation, as a file based version where files are backed up to a zip archive" },
    { word: "DataRecovery", def: "Is the process of trying to restore data after an unexpected event that results in data loss or corruption" },
    { word: "DataTapes", def: "The standard medium for archival backup data storage" },
    { word: "DetectionMeasure", def: "The measures to alert you and your team that a disaster has occurred that can impact operations" },
    { word: "DifferentialBackup", def: "A backup of files that are changed, or has been created since the last full backup" },
    { word: "DisasterRecoveryPlan", def: "A collection of documented procedures and plans on how to react and handle an emergency or disaster scenario, from the operational perspective" },
    { word: "DisasterRecoveryTesting", def: "A regular exercise that happens once a year or so, that has different teams, including IT support specialists, going through simulations of disaster events" },
    { word: "FileCompression", def: "The files and folder structures are copied and put into an archive" },
    { word: "FullBackup", def: "The full unmodified contents of all files to be backed up is are included in this backup mechanism whether the data was modified or not" },
    { word: "NASDevice", def: "A network attached storage device that has hard drives to automatically create backups and store data" },
    { word: "PreventativeMeasures", def: "Any procedures or systems in place that will proactively minimize the impact of a disaster" },
    { word: "PostMortem", def: "A way for you to document any problems you discovered along the when recovering data, and the ways you fixed them so you can make sure they don't happen again" },
    { word: "RAID", def: "A method of taking multiple physical disks and combining them into one large virtual disk" },
    { word: "RestorationProcedures", def: "A recovery process and process needs to be tested regularly that is documented and accessible so that anyone with the right access can restore operation when needed" },
    { word: "RiskAssessment", def: "Allows you to prioritize certain aspects of the organization that are more at risk if there’s an unforeseen event" },
    // security terms:

];

export const securityTerms = [
    { word: "Adware", def: "Software that displays advertisements and collects data" },
    { word: "Attack", def: "An actual attempt at causing harm to a system" },
    { word: "Availability", def: "Means that the information we have is readily accessible to those people that should have it" },
    { word: "Backdoor", def: "A way to get into a system if the other methods to get in a system aren't allowed, it's a secret entryway for attackers" },
    { word: "Baiting", def: "An attack that happens through actual physical contact, enticing a victim to do something" },
    { word: "Botnet", def: "A collection of one or more Bots" },
    { word: "Bots", def: "Machines compromised by malware that are utilized to perform tasks centrally controlled by an attacker" },
    { word: "Brute force attacks", def: "A common password attack which consists of just continuously trying different combinations of characters and letters until one gets access" },
    { word: "CIA Triad", def: "Confidentiality, integrity, and availability. Three key principles of a guiding model for designing information security policies" },
    { word: "Confidentiality", def: "Keeping things hidden" },
    { word: "Cross-site scripting (XSS)", def: "A type of injection attack where the attacker can insert malicious code and target the user of the service" },
    { word: "Denial-of-Service (DoS) attack", def: "An attack that tries to prevent access to a service for legitimate users by overwhelming the network or server" },
    { word: "Dictionary attack", def: "A type of password attack that tries out words that are commonly used in passwords, like password, monkey, football" },
    { word: "Distributed Denial-of-Service (DDoS) attack", def: "A DoS attack using multiple systems" },
    { word: "DNS Cache Poisoning Attack", def: "It works by tricking a DNS server into accepting a fake DNS record that will point you to a compromised DNS server" },
    { word: "Evil twin", def: "The premise of an evil twin attack is for you to connect to a network that is identical to yours but that is controlled by an attacker. Once connected to it, they will be able to monitor your traffic" },
    { word: "Exploit", def: "Software that is used to take advantage of a security bug or vulnerability" },
    { word: "Hacker", def: "Someone who attempts to break into or exploit a system" },
    { word: "Half-open attacks", def: "A way to refer to SYN floods" },
    { word: "Injection attacks", def: "A common security exploit that can occur in software development and runs rampant on the web, where an attacker injects malicious code" },
    { word: "Integrity", def: "Means keeping our data accurate and untampered with" },
    { word: "Keylogger", def: "A common type of spyware that's used to record every keystroke you make" },
    { word: "Logic bomb", def: "A type of Malware that's intentionally installed" },
    { word: "Malware", def: "A type of malicious software that can be used to obtain your sensitive information or delete or modify files" },
    { word: "Meddler in the middle (formerly known as Man in the Middle)", def: "An attack that places the attacker in the middle of two hosts that think they're communicating directly with each other" },
    { word: "Password attacks", def: "Utilize software like password crackers that try and guess your password" },
    { word: "Phishing attack", def: "It usually occurs when a malicious email is sent to a victim disguised as something legitimate" },
    { word: "Ping flood", def: "It sends tons of ping packets to a system. If a computer can't keep up with this, then it's prone to being overwhelmed and taken down" },
    { word: "Ransomware", def: "A type of attack that holds your data or system hostage until you pay some sort of ransom" },
    { word: "Risk", def: "The possibility of suffering a loss in the event of an attack on the system" },
    { word: "Rogue Access Point (AP) Attack", def: "An access point that is installed on the network without the network administrator's knowledge" },
    { word: "Rootkit", def: "A collection of software or tools that an admin would use" },
    { word: "Screen lock", def: "A security feature that helps prevent unwanted access by creating an action you have to do to gain entry" },
    { word: "Session hijacking (cookie hijacking)", def: "A common meddler in the middle attack" },
    { word: "Social engineering", def: "An attack method that relies heavily on interactions with humans instead of computers" },
    { word: "Spear phishing", def: "Phishing that targets individual or group - the fake emails may contain some personal information like your name, or the names of friends or family" },
    { word: "Spoofing", def: "When a source is masquerading around as something else" },
    { word: "Spyware", def: "The type of malware that's meant to spy on you" },
    { word: "SQL Injection Attack", def: "An attack that targets the entire website if the website is using a SQL database" },
    { word: "SYN flood", def: "The server is bombarded with SYN packets" },
    { word: "Tailgating", def: "Gaining access into a restricted area or building by following a real employee in" },
    { word: "Threat", def: "The possibility of danger that could exploit a vulnerability" },
    { word: "Trojan", def: "Malware that disguises itself as one thing but does something else" },
    { word: "Viruses", def: "The best known type of malware" },
    { word: "Vulnerability", def: "A flaw in the system that could be exploited to compromise the system" },
    { word: "Worms", def: "They are similar to viruses except that instead of having to attach themselves onto something to spread, worms can live on their own and spread through channels like the network" },
    { word: "0-Day Vulnerability (Zero Day)", def: "A vulnerability that is not known to the software developer or vendor, but is known to an attacker" },
    { word: "Access Control Entries", def: "The individual access permissions per object that make up the ACL" },
    { word: "Access Control List (ACL)", def: "It is a way of defining permissions or authorizations for objects" },
    { word: "Accounting", def: "Keeping records of what resources and services your users access or what they did when they were using your systems" },
    { word: "Auditing", def: "It involves reviewing records to ensure that nothing is out of the ordinary" },
    { word: "Authentication", def: "A crucial application for cryptographic hash functions" },
    { word: "Authentication server (AS)", def: "It includes the user ID of the authenticating user" },
    { word: "Authorization", def: "It pertains to describing what the user account has access to or doesn't have access to" },
    { word: "Bind", def: "It is how clients authenticate to the server" },
    { word: "Biometric authentication", def: "Authentication that uses Biometric data" },
    { word: "Certificate Revocation List (CRL)", def: "A means to distribute a list of certificates that are no longer valid" },
    { word: "Client certificates", def: "They operate very similarly to server certificates but are presented by clients and allow servers to authenticate and verify clients" },
    { word: "Counter-based tokens", def: "They use a secret seed value along with the secret counter value that's incremented every time a one-time password is generated on the device" },
    { word: "Data information tree", def: "A structure where objects will have one parent and can have one or more children that belong to the parent object" },
    { word: "Distinguished name (DN)", def: "A unique identifier for each entry in the directory" },
    { word: "Extensible authentication protocol (EAP over LAN, or EAPOL)", def: "A standard authentication protocol" },
    { word: "Identification", def: "The idea of describing an entity uniquely" },
    { word: "Kerberos", def: "A network authentication protocol that uses tickets to allow entities to prove their identity over potentially insecure channels to provide mutual authentication" },
    { word: "Lightweight Directory Access Protocol (LDAP)", def: "An open industry-standard protocol for accessing and maintaining directory services; the most popular open-source alternative to the DAP" },
    { word: "Multifactor authentication (MFA)", def: "A system where users are authenticated by presenting multiple pieces of information or objects" },
    { word: "Network time protocol (NTP)", def: "A network protocol used to synchronize the time between the authenticator token and the authentication server" },
    { word: "OAuth", def: "An open standard that allows users to grant third-party websites and applications access to their information without sharing account credentials" },
    { word: "One-time password (OTP)", def: "A short-lived token, typically a number that's entered along with a username and password" },
    { word: "One-time password (OTP) tokens", def: "Another very common method for handling multifactor" },
    { word: "OpenID", def: "An open standard that allows participating sites known as Relying Parties to allow authentication of users utilizing a third party authentication service" },
    { word: "Organizational units (OUs)", def: "Folders that let us group related objects into units like people or groups to distinguish between individual user accounts and groups that accounts can belong to" },
    { word: "Physical tokens", def: "They take a few different forms, such as a USB device with a secret token on it, a standalone device which generates a token, or even a simple key used with a traditional lock" },
    { word: "Remote Authentication Dial-in User Service (RADIUS)", def: "A protocol that provides AAA services for users on a network" },
    { word: "Risk mitigation", def: "Understanding the risks your systems face, take measures to reduce those risks, and monitor them" },
    { word: "Security keys", def: "Small embedded cryptoprocessors, that have secure storage of asymmetric keys and additional slots to run embedded code" },
    { word: "Single Sign-on (SSO)", def: "An authentication concept that allows users to authenticate once to be granted access to a lot of different services and applications" },
    { word: "StartTLS", def: "It permits a client to communicate using LDAP v3 over TLS" },
    { word: "TACACS+", def: "It is a device access AAA system that manages who has access to your network devices and what they do on them" },
    { word: "Ticket granting service (TGS)", def: "It decrypts the Ticket Granting Ticket using the Ticket Granting Service secret key, which provides the Ticket Granting Service with the client Ticket Granting Service session key" },
    { word: "Time-based token (TOTP)", def: "A One-Time-Password that's rotated periodically" },
    { word: "U2F (Universal 2nd Factor)", def: "It's a standard developed jointly by Google, Yubico and NXP Semiconductors that incorporates a challenge-response mechanism, along with public key cryptography to implement a more secure and more convenient second-factor authentication solution" },
    { word: "Unbind", def: "It closes the connection to the LDAP server" },
    { word: "XTACACS", def: "It stands for Extended TACACS, which was a Cisco proprietary extension on top of TACACS" },
    { word: "Activation threshold", def: "Triggers a pre-configured action when it is reached and will typically block the identified attack traffic for a specific amount of time" },
    { word: "Analyzing logs", def: "The practice of collecting logs from different network and sometimes client devices on your network, then performing an automated analysis on them" },
    { word: "CCMP (counter mode CBC-MAC protocol)", def: "A mode of operation for block ciphers that allows for authenticated encryption" },
    { word: "Correlation analysis", def: "The process of taking log data from different systems, and matching events across the systems" },
    { word: "Dynamic ARP inspection (DAI)", def: "A feature on enterprise switches that prevents certain types of attacks" },
    { word: "EAP-TLS", def: "One of the more common and secure EAP methods" },
    { word: "Extensible authentication protocol (EAP over LAN, or EAPOL)", def: "A standard authentication protocol" },
    { word: "Fail to ban", def: "A common open source flood guard protection tool" },
    { word: "Flood guards", def: "Provide protection against DoS or Denial of Service Attacks" },
    { word: "Four-Way Handshake", def: "It is designed to allow an AP to confirm that the client has the correct pairwise master key in a WPA-PSK setup without disclosing the PMK" },
    { word: "GTK (Groupwise Transient Key)", def: "A temporal key, which is actually used to encrypt data" },
    { word: "Hubs", def: "Devices that serve as a central location through which data travels through; a quick and dirty way of getting packets mirrored to your capture interface" },
    { word: "Implicit deny", def: "A network security concept where anything not explicitly permitted or allowed should be denied" },
    { word: "Intrusion detection and intrusion protection systems (IDS/IPS)", def: "Operates by monitoring network traffic and analyzing it" },
    { word: "IP source guard (IPSG)", def: "It can be enabled on enterprise switches along with DHCP snooping" },
    { word: "Logs analysis systems", def: "They are configured using user-defined rules to match interesting or atypical log entries" },
    { word: "Monitor mode", def: "It allows to scan across channels to see all wireless traffic being sent by APs and clients" },
    { word: "Network hardening", def: "Is the process of securing a network by reducing its potential vulnerabilities through configuration changes, and taking specific steps" },
    { word: "Network separation (network segmentation)", def: "A good security principle for an IT support specialists to implement. It permits more flexible management of the network, and provides some security benefits. This is the concept of using VLANs to create virtual networks for different device classes or types" },
    { word: "Network software hardening", def: "Includes things like firewalls, proxies, and VPNs" },
    { word: "OES (Operating Encounter Mode)", def: "It turns a block cipher into a stream cipher by using a random seed value along with an incrementing counter to create a key stream to encrypt data with" },
    { word: "Packet sniffing (packet capture)", def: "The process of intercepting network packets in their entirety for analysis" },
    { word: "Pairwise Transient Key (PTK)", def: "It is generated using the PMK, AP nonce, Client nonce, AP MAC address, and Client MAC address" },
    { word: "PBKDF2 (Password Based Key Derivation Function 2)", def: "Password Based Key Derivation Function 2" },
    { word: "PIN authentication method", def: "It uses PINs that are eight-digits long, but the last digit is a checksum that's computed from the first seven digits" },
    { word: "Port mirroring", def: "Allows the switch to take all packets from a specified port, port range, or the entire VLAN and mirror the packets to a specified switch port" },
    { word: "Post-fail analysis", def: "Investigating how a compromise happened after the breach is detected" },
    { word: "Pre-shared key", def: "It's the Wi-Fi password you share with people when they come over and want to use your wireless network" },
    { word: "Promiscuous mode", def: "A type of computer networking operational mode in which all network data packets can be accessed and viewed by all network adapters operating in this mode" },
    { word: "Proxy", def: "Can be useful to protect client devices and their traffic. They also provide secure remote access without using a VPN" },
    { word: "Rainbow tables", def: "A pre-computed table of all possible password values and their corresponding hashes" },
    { word: "Reverse proxy", def: "A service that might appear to be a single server to external clients, but actually represents many servers living behind it" },
    { word: "Rogue DHCP server attack", def: "An attacker can hand out DHCP leases with whatever information they want by deploying a rogue DHCP server on your network, setting a gateway address or DNS server, that's actually a machine within their control" },
    { word: "Tcpdump", def: "It's a super popular, lightweight command-line based utility that you can use to capture and analyze packets" },
    { word: "TKIP (Temporal Key Integrity Protocol)", def: "To address the shortcomings of WEP security" },
    { word: "VPNs", def: "Commonly used to provide secure remote access, and link two networks securely" },
    { word: "WEP (Wired Equivalent Privacy)", def: "First security protocol introduced for Wi-FI networks" },
    { word: "Wireshark", def: "It's another packet capture and analysis tool that you can use, but it's way more powerful when it comes to application and packet analysis, compared to tcpdump" },
    { word: "WPA (Wi-fi protected access)", def: "Designed as a short-term replacement that would be compatible with older WEP-enabled hardware with a simple firmware update" },
    { word: "WPA2 Enterprise", def: "It's an 802.1x authentication to Wi-Fi networks" },

];

// typewriter, clip text, transparencybg,  gradientLTR - will it chase the text as it is typed?
