export const wordsDefs = [
    { word: "Absolute path", def: "It is one that starts from the main directory" },
    { word: "Alias", def: "A nickname for common commands" },
    { word: "Appending flags", def: "A way to add the data of the file without erasing existing data" },
    { word: "Bash", def: "The language used to interact with the shell" },
    { word: "CLI", def: "Command line interpreter" },
    { word: "Command line", def: "A text interface program for a computer that inputs text commands and translates them to the operating system" },
    { word: "Escape characters", def: "A concept that means that the next character after the back tick should be treated literally" },
    { word: ".exe", def: "A file extension found in Windows for an executable file " },
    { word: "Groups", def: "A collection of users" },
    { word: "GUI", def: "A graphical user interface" },
    { word: "Hidden files", def: "A set of files that are not visible either to avoid alteration or simply because you don’t want someone to see them" },
    { word: "Hot key", def: "A keyboard shortcut that does a particular task" },
    { word: "I/O Streams", def: "An input stream handles data flowing into and out of a program" },
    { word: "Parameter", def: "A value that is associated with a command " },
    { word: "Parent directory & child directories", def: "A parent directory is a directory that houses all subsequent child directories" },
    { word: "Paths", def: "A main directory that branches off and holds other directories and files" },
    { word: "Prompt", def: "A prompt shows you which directory you’re currently in" },
    { word: "Regular expression", def: "A pattern matching language that describes words, phrases, or more complicated patterns; regular expressions are used to help you do advanced pattern based selection" },
    { word: "Relative path", def: "It is a path from your current directory" },
    { word: "Root directory", def: "A parent directory for all other directories in a file system" },
    { word: "Shell", def: "A shell is a command line interpreter for Linux" },
    { word: "Standard error (stderr)", def: "A data stream that redirect the output of error messages in a different output stream. It works both in Linux and Windows" },
    { word: "Standard In (stdin)", def: "A data stream in which the input that you provide through the keyboard goes to the standard in stream of the process that you're interacting with. It works both in Linux and Windows" },
    { word: "Standard out (stdout)", def: "A data stream that when a process creates output, it adds data to the standard out stream, which flows out of the process. It works both in Linux and Windows" },
    { word: "Stdin, stdout, stderr", def: "Three data streams created when you launch a Linux command" },
    { word: "Subdirectories", def: "A directory below or at a deeper level in the directory hierarchy" },
    { word: "Tab completion", def: "A way to auto-complete a command or file names and directories " },
    { word: "Wildcard", def: "A character that is used to help select files based on a certain pattern" },
    { word: "Windows Search service", def: "A service that indexes files on your computer by looking through them on a schedule" },
    { word: "ACL", def: "Access Control Lists" },
    { word: "Administrator", def: "A user that has complete control over a machine" },
    { word: "Biometric data", def: "A way of protecting your accounts and information using biometric data such as facial recognition and fingerprint" },
    { word: "Computer management", def: "A tool that lets you manage a local or remote computer" },
    { word: "DACL", def: "Discretionary Access Control List" },
    { word: "File permissions", def: "A process for setting permissions for who has access to certain files" },
    { word: "Full control", def: "A user or group with full control that can do anything they want to files" },
    { word: "Inherit only", def: "A permission group that means that a DACL will be inherited, but not applied to a container" },
    { word: "List folder contents", def: "A command that will execute and list folder contents and is an alias for Read and Execute" },
    { word: "Mobile device management", def: "A system used to apply and enforce rules about how the device has to be configured and used" },
    { word: "Modify", def: "An umbrella permission that includes read and execute and write" },
    { word: "Primary account", def: "The initial account you made during setup" },
    { word: "Read and execute permission", def: "Permissions that grant you access to read the file that exists and execute it if its runnable" },
    { word: "Read permission", def: "Permissions that grant you access to read the file that exists" },
    { word: "Root user", def: "It is the first user that gets automatically created when we install a Linux OS and has all the privileges on the OS. Also called the super user. There's technically only one superuser or root account, but anyone that's granted access to use their powers can be called a superuser too" },
    { word: "SACL’s", def: "System Access Control List" },
    { word: "Simple permissions", def: "Special or specific permissions" },
    { word: "Single sign on (SSO)", def: "An account that grants you access to multiple accounts without require constant entry of a password or username" },
    { word: "Standard user", def: "A user who is given access to the machine but has restricted access to do thing like install software or change certain setting" },
    { word: "Windows domain", def: "A network of computers and users that are added to a central database" },
    { word: "Write permission", def: "A permission that allows you to make changes to a file" },
    { word: "App Store apps", def: "A Package Manager that acts as a repository" },
    { word: "App store repository", def: "A app store service that also acts as a repository" },
    { word: "App stores", def: "A central managed marketplace for app developers to publish and sell mobile apps" },
    { word: "APPX", def: "An APPX is another way to package contents of a file to act like a unit of distribution" },
    { word: "Archive", def: "An archive is comprised of one or more files that are compressed into a single file" },
    { word: "Block devices", def: "A system that acts like USB drives and hard drive by transmitting data" },
    { word: "Cache", def: "The assigned stored location for recently or frequently accessed data; on a mobile app it is where anything that was changed or created with that app is stored " },
    { word: "Character devices", def: "A way to transmit data character by character like a keyboard and mouse" },
    { word: "Chocolatey", def: "A third party package manager for Windows" },
    { word: "Closed source packages", def: "A source code that does not allow public access" },
    { word: "Debian(.deb)", def: "A Debian package is packaged as a .deb file" },
    { word: "Device manager", def: "A console management system for your device" },
    { word: "Driver", def: "Used to help our hardware devices interact with our Operating System" },
    { word: "Dynamic-link libraries", def: "Programs that want to use functionality that the code provides can tap into it if they need to (shared libraries) " },
    { word: "Enterprise app management", def: "A management system that allows an organization to distribute custom mobile apps" },
    { word: "Executable file", def: "A file containing instructions for a computer to execute when they’re run" },
    { word: "Hardware ID", def: "A special string of characters assigned to hardware" },
    { word: "Having dependencies", def: "A process of counting on other pieces of software to make an application work since one bit of code depends on another in order to work" },
    { word: "Installing from source", def: "A process of installing from a source" },
    { word: "Kernel module", def: "It extends the kernel's functionality so developers don't have to actually touch the Linux kernel" },
    { word: "Library", def: "A way to package a bunch of useful code that someone else wrote" },
    { word: "Manifest", def: "A library used if an application needs to use a shared library" },
    { word: "Microsoft Install Package(.msi) and MSI files", def: "Microsoft Install Package is a file extension used to guide a program called Windows Installer in the installation, maintenance, and removal of programs of the windows operating systems. MSI files are a combination of of databases that contain installation instructions in different tables along with all the files" },
    { word: "Mobile applications", def: "Software that is distributed on mobile OS devices " },
    { word: "Packaged archives", def: "The core or source software files that are compressed into one file" },
    { word: "Packaged managers", def: "An application that makes package installation and removal easier" },
    { word: "Personal package archives", def: "A software repository for uploading source packages to be built and published " },
    { word: "Portable Executable (PE) format", def: "Windows unique version of .exe" },
    { word: "Process monitoring", def: "A way of monitoring what processes are happening during installation" },
    { word: "Repository", def: "A server that acts like a central storage location for packages" },
    { word: "SD devices", def: "Mass storage devices like hard drives" },
    { word: "Security patch", def: "A piece of software that is meant to fix up a security hole" },
    { word: "Side-by-side assemblies", def: "A system that manages most shared libraries and resources on Windows and supports access to multiple versions of the same shared library automatically" },
    { word: "Side-loading", def: "A process of installing mobile apps directly without using an app store" },
    { word: "Sysinternals package", def: "A set of tools released by Microsoft that can help you troubleshoot" },
    { word: "Windows store", def: "A Windows store is an application repository or warehouse where you can download and install universal Windows platform apps" },
    { word: "Windows update client service", def: "System that runs in the background on your computer to download and install updates and patches for your operating system" },
    { word: "Command line mode", def: "When you are able to run commands while still in your current shell" },
    { word: "Data", def: "Actual content of a file" },
    { word: "Data buffer", def: "A region of RAM that’s used to temporarily store data while it’s being moved around" },
    { word: "Defragmentation", def: "A process of taking all the files stored on a given disk and reorganizing them into neighboring locations" },
    { word: "Disk Management utility", def: "Native tool for Windows that helps with managing disk space" },
    { word: "File record number", def: "The index of the files entry in the MFT" },
    { word: "File system", def: "Used to keep track of files and file storage on a disk" },
    { word: "Hard link", def: "When created in NTFS, an entry is added to the MFT that points to the linked file record number, not the name of the file. This means the file name of the target can change and the hard link will still point to it" },
    { word: "Inode", def: "A file structure for metadata and files" },
    { word: "Interactive mode", def: "When the parted tool launches you into a separate program" },
    { word: "Master boot record (MBR)", def: "a traditional partition table within a storage disk that lets you have volume sizes of 2 terabytes or less and is mostly used in the Windows OS" },
    { word: "Master file table (MFT)", def: "A way NTFS stores and represents the files you’re working with on your operating system" },
    { word: "Memory manager", def: "A Windows OS program that helps manage virtual memory " },
    { word: "Metadata", def: "Tells us everything we need to know about a file, including who created it, when it was last modified, who has access to it, and what type of file it is." },
    { word: "Mounting", def: "Making a file or hard disk accessible to the computer" },
    { word: "Partition table", def: "How the disk is partitioned on an OS" },
    { word: "Shortcut", def: "An entry in the MFT that has a reference to some destination, so that when you open it up, you get taken to that destination" },
    { word: "Softlinks", def: "A shortcut in Linux, that allows us to link to another file using a file name" },
    { word: "Swap space", def: "The allocated space where the virtual memory is stored on the hard drive when the amount of physical memory space is used up or full" },
    { word: "Symbolic links", def: "Work similarly to shortcuts, but at the file system level. The key difference is that the operating system treats them like substitutes for the file they're linked to in almost every meaningful way" },
    { word: "System properties", def: "A control panel applet that allows you to edit the size and number and location of paging files" },
    { word: "Trim", def: "A command to delete unused data blocks so the space can be used for the computer’s storage needs" },
    { word: "UEFI", def: "A new standard for BIOS" },
    { word: "UUID", def: "Universally Unique ID" },
    { word: "Virtual memory", def: "A combination of hard drive space and RAM that acts like memory which our processes can use" },
    { word: "Volume", def: "A format for a filesystem on a partition" },
    { word: "Background processes/Daemon processes", def: "Processes that run or take place in the background" },
    { word: "Client/Server runtime subsystem", def: "System that handles running Windows GUI and Command line" },
    { word: "Environment", def: "Whatever settings or variables a child process inherits from the parent’s process" },
    { word: "Multilingual user interface", def: "Interface that offers and support different languages" },
    { word: "Processes", def: "Help the computer run programs " },
    { word: "Process Explorer", def: "A utility Microsoft created to let IT support specialists and system administrators look at running processes" },
    { word: "Process ID", def: "Unique identifier for processes on your computer" },
    { word: "Programs", def: "The applications that we can run" },
    { word: "Resource monitoring", def: "The most common way to quickly take a peek at how system resources are doing" },
    { word: "Session manager subsystem", def: "Process that is in charge of setting some stuff up to work for the OS" },
    { word: "Signal", def: "A way to tell a process that something has just happened" },
    { word: "Suspended apps", def: "A command that will tell the OS to suspend background mobile apps" },
    { word: "Task Manager", def: "A Windows utility that allows you to gain information about what tasks you have running in the background " },
    { word: "Termination signal", def: "A kill command that will stop whatever process you tell it to" },
    { word: "Cloud computing", def: "The concept and technological approach of accessing data, using applications, storing files, etc. from anywhere in the world as long as you have an internet connection" },
    { word: "Data center", def: "A facility that stores hundreds, if not thousands of servers" },
    { word: "Deployment", def: "Hardware is set up so that the employee can do their job" },
    { word: "IT Infrastructure", def: "The software, the hardware, network, and services required for an organization to operate in an enterprise IT environment" },
    { word: "KVM Switch", def: "Keyboard, video, & mouse switch that looks like a hub that you can connect multiple computers to and control using one keyboard, mouse, and monitor" },
    { word: "Maintenance", def: "Where software is updated and hardware issues are fixed if, and when, they occur" },
    { word: "Procurement", def: "Hardware is purchased or reused for an employee" },
    { word: "Production", def: "The parts of the infrastructure where certain services are executed and serve to its users production" },
    { word: "Reproduction case", def: "Recreating an error to test a solution to make sure the problem is gone after a fix has been applied" },
    { word: "Retirement", def: "Hardware becomes unusable or no longer needed, and it needs to be properly removed from the fleet" },
    { word: "Rollback", def: "Reverting to the previous state before you made changes" },
    { word: "Secondary or stand-by machine", def: "A machine that is the same as a production machine, but won't receive any traffic from actual users until enabled" },
    { word: "Server", def: "Software or a machine that provides services to other software or machines" },
    { word: "System Administration", def: "The field in IT that is responsible for maintaining reliable computer systems, in a Multi-user environment" },
    { word: "Test environment", def: "A virtual machine running the same configuration as a production environment, but isn't actually serving any users of the service" },
];